name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      placeholder:
        description: 'placeholder, no effect'
        required: false
jobs:

  release_master:
    name: Master
    runs-on: [self-hosted, linux]
    steps:
    - name: Fix permissions
      run: |
        docker run --rm -v $PWD:/p -w /p busybox chmod -R o+w .
        docker run --rm -v $HOME/ci-tmp/:$HOME/ci-tmp/ busybox rm -rf $HOME/ci-tmp/wheelhouse
    - uses: actions/checkout@v2
    - name: Setup submodule
      uses: ./.github/actions/setup
    - name: Build OneFlow
      run: |
        ONEFLOW_CI_PACKAGE_SUFFIX="_cu102" \
        ONEFLOW_CI_PYTHON_VERSION_ARGS=" " \
        bash ci/build/make.sh
        $HOME/ $HOME/ci-tmp/wheelhouse
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        git_branch=${GITHUB_REF##*/}
        $HOME/ossutil64 cp --update -r $HOME/ci-tmp/wheelhouse oss://oneflow-static/${git_branch}/${git_hash}
